### ISSUE TITLE
No releases tagged

### ISSUE THREAD

**Issue by ollieparanoid** [AsteroidOS/msm-fb-refresher#1]
We would like to package `msm-fb-refresher` for our Linux distribution (https://github.com/postmarketOS/pmbootstrap/issues/584).

While we can package it with a commit hash as version, it would be nicer if the program had a proper release version. Could you tag the last commit as a release (e.g. `0.1.` or something)?

Thank you for making this program!

**Comment by FlorentRevest** [comment]
Hi Oliver,
Glad to know this program helped you. You should now be able to find a v0.1 tag pointing to the latest commit https://github.com/AsteroidOS/msm-fb-refresher/releases/tag/v0.1

All the best with your project,
    Florent
